### ISSUE TITLE
Keeping ROI Markers' Size Constant / Exporting Values for Entire Stack

### ISSUE THREAD

**Issue by AlexMorello** [tanguyduval/imtool3D_td#10]
Dear Tanguy,

first and foremost, I'd like to thank you for developing and maintaining the tool, and also for contributing to the life-saving [_qMRLab_](https://github.com/qMRLab/qMRLab) project. So is it possible to export the statistics for the entire stack, and can you keep the size of the ROI markers constant across the whole image? As in, copy-and-paste the same marker onto various regions of interest?

**Comment by tanguyduval** [comment]
Hi,
Thank you for your kind words. 

If you are using the same ROI on your entire stack (same color, e.g. red for label '1'), the statistics button (qMRLab: on the left. standalone imtool3d: on the right ![image](https://user-images.githubusercontent.com/7785316/151664379-0f508ab1-8b2b-455b-903f-f017c8b6dc72.png)) gives you the statistics of the entire stack.

If you want to propagate an ROI on multiple slice. You can draw on the first and last slice (using the same color) and use the `slice interpolation tool` (![image](https://github.com/tanguyduval/imtool3D_td/blob/master/src/icon_interpmask.png?raw=true))

Does that answers your question?

Regards

**Comment by AlexMorello** [comment]
So basically here's the deal: I need to read out the mean from the middle of each hole so that the marker is the same size for each hole, and I need to do that for each slice. The holes are more than the labels, btw.
![Screenshot from 2022-01-29 16-36-54](https://user-images.githubusercontent.com/84672824/151667151-a18c012b-4ca0-4889-bfe9-3efcd947551b.png)
.

**Comment by tanguyduval** [comment]
To do that:
- Une only one circle: 
![image](https://user-images.githubusercontent.com/7785316/151673562-6264858d-2c83-4d5c-84cd-bad60f725502.png)
- poly2mask to draw label `1`:
![image](https://user-images.githubusercontent.com/7785316/151673608-f533e032-325d-4d37-96f4-e351063b4992.png)
- Move around your circle
- change label (you can access any label through right click on label `5`>`set value`, or simply enter shortcut key `6` for instance)
- `poly2mask`
- Finally you get
![image](https://user-images.githubusercontent.com/7785316/151673663-55159250-a52e-47f7-8f4f-0e895823e2b8.png)
- If you have multiple slices:
- Repeat the same exercice on the last slice
- Finally use the slice interp tool: 
![image](https://user-images.githubusercontent.com/7785316/151673833-fc2b395f-51f7-4dfd-93db-ff2c5eba0843.png)


Best

**Comment by tanguyduval** [comment]
To do that:
- Une only one circle: 
![image](https://user-images.githubusercontent.com/7785316/151673562-6264858d-2c83-4d5c-84cd-bad60f725502.png)
- poly2mask to draw label `1`:
![image](https://user-images.githubusercontent.com/7785316/151673608-f533e032-325d-4d37-96f4-e351063b4992.png)
- Move around your circle
- change label (you can access any label through right click on label `5`>`set value`, or simply enter shortcut key `6` for instance)
- `poly2mask`
- Finally you get
![image](https://user-images.githubusercontent.com/7785316/151673663-55159250-a52e-47f7-8f4f-0e895823e2b8.png)
- If you have multiple slices:
- Repeat the same exercice on the last slice
- Finally use the slice interp tool: 
![image](https://user-images.githubusercontent.com/7785316/151673833-fc2b395f-51f7-4dfd-93db-ff2c5eba0843.png)


Best

**Comment by AlexMorello** [comment]
I seem to be getting combined stats by doing this, not those for each slice

**Comment by tanguyduval** [comment]
To understand, you want one value per slice and per tube, isn't it?

**Comment by AlexMorello** [comment]
I actually need all the values for all the tubes of each slice, as in: slice 1, tube 1, tube 2, ..., tube 6 ; slice 2, tube 1, tube 2, ..., tube 6; and so on.

**Comment by tanguyduval** [comment]
To do that, a workaround is to turn your 3D volume of `N` slices into `N` different images.
For that aim:
- Turn your volume into different images by entering the following command in the Matlab command window:
````matlab
S = guidata(findobj('Tag','qMRILab')); tool=S.tool; % get viewer object 'tool' in qMRLab
tool.setImage(permute(tool.getImage,[1 2 4 5 3])); %turn 3D into N 2D images 
tool.setlabel(strsplit(num2str(1:length(tool.getImage(1))),' ')) % Name each image '1', '2', '3'...
````
- Draw your ROI in the different tubes in different colors
- Finally use the statistics button  

You will have the stats for each color and in each slice.
Tell me if it worked for you

Best

**Comment by AlexMorello** [comment]
Dear Tanguy, 

Thank you for the suggestion! I'm back on the track after a long leave of absence. Here is what I'm getting, though: 

```
Error using xlim (line 31)
Limits must be a 2-element vector of increasing numeric values.

Error in imtool3D/setImage (line 907)
                    xlim(tool.handles.HistAxes,[tool.centers(1) tool.centers(end)+.1])]
```

**Comment by tanguyduval** [comment]
Hi Alex,

Can you try to load your image (example: `image.nii`) and display it in an independant viewer instance please:
````matlab
dat = nii_load('image.nii');
dat = permute(dat,[1 2 4 5 3]); %turn 3D into N 2D images
tool = imtool3D(dat);
tool.setlabel(strsplit(num2str(1:size(dat,5)),' ')) % Name each image '1', '2', '3'...
````

Then proceed to the labelling as I explained above.
Regards
