### ISSUE TITLE
Label Overlapping

### ISSUE THREAD

**Issue by AlexMorello** [tanguyduval/imtool3D_td#11]
Dear Tanguy,

May I ask how you deal with label overlapping in the viewer? 

![mean](https://user-images.githubusercontent.com/84672824/170886414-129c946f-cafe-4830-8937-ed0cd93a28f0.png)

**Comment by tanguyduval** [comment]
Dear Alex, 

you can only hide a label through right click on red marker > hide label.

Hope this solution will help
Regards

**Comment by AlexMorello** [comment]
Great, thank you very much!
