### ISSUE TITLE
Error in imtool3D

### ISSUE THREAD

**Issue by hajerkr** [tanguyduval/imtool3D_td#12]
Hello,

I am trying to launch imtool3D on matlab, but I get an odd error. 

The command is `tool=imtool3D(mask);` . The mask variable is a 91x109x91 _single_ matrix. I tried with a 256x256x332  _uint16_ matrix, same error

<img width="573" alt="image" src="https://user-images.githubusercontent.com/13291010/192621152-fe50b13a-d84f-4a53-b120-dd6850c04616.png">

I am using MatlabR2019a.

Thanks

**Comment by tanguyduval** [comment]
Hi Hajer,

Yes, this is an error!
Solved it in last version with the following change in imtool3D.m:

````diff
- if ~ispref('imtool3D','ScrollWheelFcn') && strfind(lower(Orient),'vertical') 
+ if ~ispref('imtool3D','ScrollWheelFcn') && ~isempty(strfind(lower(Orient),'vertical')) 
````
              
Thank you for pointing this out.
Tell me if this solved your problem and if you have other issues please.

Best

**Comment by hajerkr** [comment]
Perfect, solved- thanks!
