### ISSUE TITLE
Question - does this GUI perform image registration?

### ISSUE THREAD

**Issue by neuropil** [tanguyduval/imtool3D_td#9]
Amazing GUI! 

Does it perform co-registration of MRI-MRI or MRI-CT?

Thanks!
John

**Comment by tanguyduval** [comment]
Hi @neuropil 

Thank you for your positive feedback :)

Do you want 
  * an automatic method
  in this case you can use [matlab registration tools](https://fr.mathworks.com/discovery/image-registration.html) such as `imregister` or third party algorithms such as [antsRegistration](https://github.com/ANTsX/ANTs) that you can access through system calls  
  * a manual method
  In this case you could use this GUI, for rigid translation only. I can document this feature if you need.

Best,
Tanguy

**Comment by tanguyduval** [comment]
@neuropil may I close this issue? Did it solved your problem?

**Comment by neuropil** [comment]
Yes! Thank you!
